# Generated by Django 3.2 on 2023-08-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='hex_code',
            new_name='color',
        ),
    ]
